### PR TITLE
[GH-1617] Unstable connection icon

### LINKED ISSUE #1617: [FEATURE] Displaying connectivity Icon for connection issues
## 🚀 Feature
In this task, we aim to show a connectivity icon on the screen to alert players when they encounter connectivity issues during gameplay. It involves researching the criteria for determining when a connection is unstable and identifying optimal moments to trigger the icon.

We can use this [icon](https://github.com/lambdaclass/curse_of_mirra/assets/6811225/81d5eb75-367f-4934-9b50-c9fc06e96bdf) in the meantime. Related to #1614

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1617 

Backend PR https://github.com/lambdaclass/mirra_backend/pull/619
## Motivation

When we have connectivity stability we have no feedback for the user

## Summary of changes
This PR:
- Adds a warning feature that shows the icon
- Adds a disconnect feature for when the connection is lost
- Adds a connectivity feature to check is the connection is stable
- Add icon in game + it's requested animation
- Block user's send action to backend until the stability is recovered, to avoid a queue of requests and bugs
- Repositions the player once the connection is stable again
- Supports airplane mode in game for both Android and IOS

DISCLAIMER: this doesn't support 3g testing. The issues when using 3g will be solved in a future iteration

https://github.com/lambdaclass/curse_of_mirra/assets/82987608/7825c16f-6acf-46a7-b882-37868992dc5c

## How has this been tested?

Setting for fake spikes:
- Open 3 terminal tabs for the back repo
- Open a terminal tab for the client PR
- In the 1st back terminal tab run: `toxiproxy-server`
- In the 2nd back terminal tab run: `export USE_PROXY=true` and then `make start`
- In the client terminal tab run: `toxiproxy-cli toxic add -n latency -t latency -a latency=300 game_proxy`
- In the 3rd back terminal tab run: `./lag_spikes.sh`

In the backend repo, go to "lag_spikes.sh":
I used the following but you can alter each value to fake your own ping spikes
```
latencies=(150 500 150 100 500 100 500 100 500 100)
latency_durations=(1 1 1 1 1 1 1 1 1 1)
```

In the client repo:
Go to "GameServerConnectionManager.cs" and "ServerConnection.cs" and change in method "makeWebsocketUrl()"
`int port = 5000; `

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by jazimp** [comment]
Looks great! Visual approval ✅

**Comment by tvillegas98** [comment]
I have to change the `spikeValueThreshold` to `3` and the ping values to 
```bash
latencies=(30 180 30 30 400 30 450)
latency_durations=(0.3 1 0.3 0.3 1 0.3 2)
```
in order to make the pop up appear.

Besides that, I'm able to use the items while I'm freeze due to the pop up

**Review by BertovDev — CHANGES_REQUESTED** [review]
Connection error keep popping up also when you are not disconnected.

**Comment by AngieDutra** [comment]
All checks will depend on timestamps. I'll do this refactor

**Comment by AngieDutra** [comment]
All checks will depend on timestamps. I'll do this refactor

**Comment by AngieDutra** [comment]
All checks will depend on timestamps. I'll do this refactor

**Review by alfopisano — COMMENTED** [review]
Testing it as a user, I founded it a little difficult to play before the icon is displayed. I can see that other players are hurting me but I see them as far behind me, what to you think?
https://github.com/lambdaclass/curse_of_mirra/assets/116388676/2b1f98e4-b231-4413-a9c9-74c90f080960

**Comment by AngieDutra** [comment]
I'll adjust the config for this

**Review by alfopisano — CHANGES_REQUESTED** [review]
I am still encountering some problems as a user when playing with bad connection. As commented above I see that other players are hurting me but I am seeing them as far behind on the arena while the icon is still not showing up: 

https://github.com/lambdaclass/curse_of_mirra/assets/116388676/f79520dc-499a-47d6-9c8e-faee55af2243

https://github.com/lambdaclass/curse_of_mirra/assets/116388676/02fb3e04-805b-4678-aa3b-79402c0abc00

**Comment by Nico-Sanchez** [comment]
We started all over in #1798

**Pull request closed without merging**
