### PR TITLE
[Gh-1964] Refactor sound manager

### LINKED ISSUE #1964: [REFACTOR] Sound manager refactor v2
## 🚧 Refactor
Refactor the current Sound Manager from TopDownEngine to utilize Unity’s built-in audio system. The new implementation should maintain all existing functionality.

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1964

## Motivation

How we handled the audio was complicated and wrong

## Summary of changes

This PR:
- Solves UI overrides in both prefabs and scenes
- Refactors how we handle toggle audios
- Refactors how we handle the persistent music in the scenes
- Adjusts how we handle SFX in a more UI / DEV friendly way
Note: this last item is a first iteration. The final goal is to stop using MMSoundManager ( issue #2002 )

## How has this been tested?

Start a match and try all sorts of sound configuration in both main screen and battle. They should persist when changing scenes and be applied as shown in the UI

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by tkz00 — CHANGES_REQUESTED** [review]
- The main screen music (lobby) doesn't loop, I just tried it in main and it seems to loop (keep in mind there are 27 seconds of no sound at the end of the lobby audio file).
- I feel there is too much of a difference between the first values of the volume and too little for the higher ones. Maybe not for this iteration, or maybe never, but I found this video really interesting that helps to understand this issue (https://www.youtube.com/watch?v=MquQQX0Ak0k)
- I think `VolumeController.cs` could be deleted, I tried it and got no errors.

**Comment by AngieDutra** [comment]
Nice vid!
- Now the music is looped
- I forgot to delete that unused script

**Comment by AngieDutra** [comment]
Yes, @alfopisano keep in mind there are 27 seconds of empty sound at the end of the lobby audio file. This will be fixed by our audio team in the future

**Review by tkz00 — APPROVED** [review]
Great! It feels much simpler and better to handle sound now! I tested on android and everything worked!

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on my iOS device and worked great

**Pull request merged**
