### PR TITLE
[VFX] Reworked Damage zone effect

### PR DESCRIPTION
**Pull request by saugon**
## Motivation

Reworked Damage zone effect. Now it has additional conus-like shape to show exect effect area and additional shadow particle to highlight main sand effect.

## Summary of changes

Added new Renderers to SafeZone.cs to control _AlphaMultiplier and _Progress parameters. Also added new objects to existing effect.

## How has this been tested?

New effect can be tested via test scene VFX_DamageZone_test_Scene.unity using DamageZoneManager.cs ore via regular gameplay

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — COMMENTED** [review]
I do not know if this is in the scope of this PR but I find it a bit weird that on the first part of the zone I do not get harmed by it: 
<video src="https://github.com/lambdaclass/champions_of_mirra/assets/116388676/ba5f7b0f-486c-4167-9e08-6c528c86bbaa" >

**Comment by saugon** [comment]
> I do not know if this is in the scope of this PR but I find it a bit weird that on the first part of the zone I do not get harmed by it:
> Screen.Recording.2024-07-10.at.14.22.50.mov

Let me check it out. I tried the same, and it seemed to work fine.​⬤

**Review by alfopisano — APPROVED** [review]
Nice!! I really like this new zone, tested on my iOS device

**Review by tkz00 — COMMENTED** [review]
Screenshot 2024-07-11 at 4 51 04 PM

Everything looks great, the only thing is that I merged main and the healthbar appears under the zone, should this be fixed here or in a future PR?

**Comment by saugon** [comment]
> Screenshot 2024-07-11 at 4 51 04 PM
> 
> Everything looks great, the only thing is that I merged main and the healthbar appears under the zone, should this be fixed here or in a future PR?

Future PR: the card-info is currently being refactored. Following that, we’ll need to adjust the render priority.

**Review by tkz00 — APPROVED** [review]
Great! Looks much better! I tested on my android!

**Pull request merged**
