### PR TITLE
UI fix buttons

### LINKED ISSUE #266: [DESIGN] Buttons fix guide
## 🎨 Design

The ideal case for managing buttons would be to establish:

1. Primary button
2. Secondary button
3. Tertiary button (if needed) 

It can have 3 sizes for each button type, depending on usage.

_Maintain consistent typography across all buttons.
Also, review cases where there are uppercase and lowercase letters and only uppercase._

### Button guide
button guide
1. Padding
6. Font size and type
7. Background color
8. Shape and shadow
9. Safety space

**Padding**: It's the distance we leave between the button title and its margins.

**Font size and type**: It's important to use a font size corresponding to the button size.

**Background color**: It should be related to the app's color palette and stand out from the general interface colors.

**Shape and Shadow**: Shadow is a useful tool for giving depth to the button compared to the rest of the interface, aiding user identification.

**Safety space**: It's the space left between the button and the rest of the interface elements.

**¡Important!** Review that there are no "duplicate" buttons, meaning that they perform the same action. For example: having a _close button_ and another one to _cancel_ the action.

This brings several problems: 
- It reduces the space that can be used to better display information.
- Confuses the user.

### PR DESCRIPTION
**Pull request by tkz00**
Closes #266 

Most buttons in the game have been set up as instances of new prefabs: primary or secondary button, to facilitate future changes, these prefabs are also a visual improvement to the previous buttons. These can be seen all throughout the game, positive buttons in all popups (such as confirming an action or going to the shop to buy more resources when the user doesn't have enough currency), level up unit button, battle button both in the campaign and lineup screens, summon, fusion and in the victory and defeat splash screens as try again and next buttons,.

Disclaimer: some buttons, mainly the ones in the equipment list popup in unit detail, remain unchanged, since visual improvement of popups will be handled in [this issue](https://github.com/lambdaclass/champions_of_mirra/issues/267).

Screenshot 2024-03-20 at 13 58 35
Screenshot 2024-03-20 at 13 58 39
Screenshot 2024-03-20 at 13 58 52
Screenshot 2024-03-20 at 13 58 59
Screenshot 2024-03-20 at 13 59 38
Screenshot 2024-03-20 at 14 00 04
Screenshot 2024-03-20 at 14 00 12
Screenshot 2024-03-20 at 14 01 14
Screenshot 2024-03-20 at 14 01 23
Screenshot 2024-03-20 at 14 01 31
Screenshot 2024-03-20 at 14 11 55

### CODE REVIEW

**Review by AngieDutra — CHANGES_REQUESTED** [review]
@tkz00 don't forget the screenshots for visual implementations 😊 
If the following are the primary and secondary buttons, I have some comments:
Captura de pantalla 2024-03-19 a la(s) 7 35 08 p  m

The OK text here needs some air on the top and bottom part
Captura de pantalla 2024-03-19 a la(s) 7 34 40 p  m

Here the issue is this button is not the same as battle. I see here a similar primary button not respecting the typology stablished by the issue
Captura de pantalla 2024-03-19 a la(s) 7 34 53 p  m

Also, overall, watch out for the typography used in the buttons. Talk it over with @jazimp and me tomorrow so we add those changes here too ✨

**Comment by jazimp** [comment]
To complete the screenshot request, while it's helpful to have the crop of each button, it would also be good to take a screenshot of the entire screen to see how everything works overall. That will make the correction process better 😊

**Comment by tkz00** [comment]
> @tkz00 don't forget the screenshots for visual implementations 😊 If the following are the primary and secondary buttons, I have some comments: Captura de pantalla 2024-03-19 a la(s) 7 35 08 p  m
> 
> The OK text here needs some air on the top and bottom part Captura de pantalla 2024-03-19 a la(s) 7 45 03 p  m
> 
> Here the issue is this button is not the same as battle. I see here a similar primary button not respecting the typology stablished by the issue Captura de pantalla 2024-03-19 a la(s) 7 34 53 p  m
> 
> Overall, watch out for the fonts used in the buttons and sizes
> 
> Small comment to add, I seem to be missing the new fonts. Thats my bad and will download them asap if they are uploaded in the asset drive

Ok, this issues have been taken care of.

**Comment by jazimp** [comment]
I see the change in the buttons applied quite well. Quick question: shouldn't the buttons for "Save" and "Load" also be modified? @tkz00 
Captura de pantalla 2024-03-20 a la(s) 14 22 00

**Comment by tkz00** [comment]
> I see the change in the buttons applied quite well. Quick question: shouldn't the buttons for "Save" and "Load" also be modified? @tkz00 Captura de pantalla 2024-03-20 a la(s) 14 22 00

Yeah, sorry, those buttons should've been removed, here is the updated look
image

**Comment by tkz00** [comment]
The popups should have an overlay behind with some opacity.

**Comment by tkz00** [comment]
> It's looking much better now, and with a better use of prefabs. I just left a suggestion to remove a log, everything else seems great.

Done!

**Review by ncontinanza — DISMISSED** [review]

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Both buttons are shown in the same way but the centerings are off. Also, the first scene screen should be a button "start" and in game with lineup should be "battle"
Captura de pantalla 2024-03-25 a la(s) 6 16 57 p  m
Captura de pantalla 2024-03-25 a la(s) 6 17 22 p  m

**Comment by tkz00** [comment]
> Both buttons are shown in the same way but the centerings are off. Also, the first scene screen should be a button "start" and in game with lineup should be "battle" Captura de pantalla 2024-03-25 a la(s) 6 16 57 p  m Captura de pantalla 2024-03-25 a la(s) 6 17 22 p  m

Should be fixed

**Review by AngieDutra — APPROVED** [review]
Awesome work here! ✨

**Review by ncontinanza — APPROVED** [review]

**Pull request merged**
