### PR TITLE
Correct skill skilcriptableObject indicator type.

### LINKED ISSUE #1535: [BUG] Fix skills input radius, width and angle
### Skills input radius
Most of the skills have the radius value hardcoded. We need to map them with the ones sent by the backend.

### Skills input width and angle
Verify that the skills angles (for the cone type) and the width (for Direction type) are correctly mapped and displayed. For example, H4ck's basic attack cone angle doesn't match the angle in which the projectiles are shot.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1535 

## Motivation

Some indicators had their indicator type wrong in their respective ScriptableObject.

## Summary of changes

- Remove old cone indicator
- Correct indicator type of some skills scriptableObject

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by tkz00** [comment]
Some have been fixed, but most indicators size's don't match with their abilities, be it for whatever reason.

**Review by tkz00 — CHANGES_REQUESTED** [review]
Some have been fixed, but most indicators size's don't match with their abilities, be it for whatever reason.

**Comment by BertovDev** [comment]
> Some have been fixed, but most indicators size's don't match with their abilities, be it for whatever reason.

Yep, we need to define some values in the config like range of projectiles abilities.

**Comment by BertovDev** [comment]
In order to fully show the correct sizes of indicators we should archive this issue : https://github.com/lambdaclass/mirra_backend/issues/431

Also some of this values changes in runtime such as the speed of the dash. It can be modified by the boots items. We also should think about that later.

**Review by agustinesco — CHANGES_REQUESTED** [review]
The valtimer's basic seems to be broken

**Comment by AngieDutra** [comment]
@alfopisano will take over this task later on

**Pull request closed without merging**
