### PR TITLE
Valtimer texture and material update

### PR DESCRIPTION
**Pull request by tkz00**
## Motivation

The Valtimer textures were outdated and needed an update.

## Summary of changes

Visual assets have beend added, removed or modified, such as textures, materials and prefabs.

## How has this been tested?

Pick Valtimer and check the character looks like the references, pay attention to it's UI model in the main screen, in character info and in the end game splash. Also there should be changes in it's in game model.

https://github.com/lambdaclass/champions_of_mirra/assets/67983386/d1681153-6dd7-40f7-9d22-fdd98b0f31a8

https://github.com/lambdaclass/champions_of_mirra/assets/67983386/a99bc07d-2a9e-469c-bc47-6f7015aba22c

## Checklist
- [X] I have tested the changes locally.
- [X] I have tested the whole game after applying the changes, not only the affected areas.
- [X] I self-reviewed the changes on GitHub, line by line.
- [X] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [X] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — DISMISSED** [review]
Nice!! Tested on my iOS device and looked great

**Review by AngieDutra — COMMENTED** [review]
Tested in desktop and Android build. Looks a bit too dark in the death splash
Screenshot 2024-07-04 at 13 59 11

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Now I see valtimer too white
Screenshot_20240704_153414_client
Screenshot_20240704_153422_client

**Review by saugon — APPROVED** [review]

**Comment by tkz00** [comment]
It was decided the new texture could have some improvements, this PR will be closed and we get the new iteration from the art team we'll open a new one.

**Pull request closed without merging**
