### PR TITLE
[GH-1766] Daily rewards screen

### LINKED ISSUE #1766: [FEATURE] Daily rewards screen
## 🚀 Feature

Implement the new design

### Reference

reference

### Assets

https://drive.google.com/drive/folders/1XM7nO1qnBEMPVFxor3A5pf7UoFWFTHDD

https://drive.google.com/drive/folders/1MChAO5LEQ4eOFrTm-sLJ8OT4nQPj5mlR?usp=drive_link

https://drive.google.com/drive/folders/18CThUAJRrYy62blR-aP36nF5OzmA_jX-?usp=drive_link

Background: 
https://drive.google.com/file/d/1WRh2KARikLv86Bwe6UE-_1S9HS4GZrRM/view?usp=drive_link

### Additional context

https://www.notion.so/lambdaclass/Daily-Login-Streak-9b9db0c820bd49f29b5c75753ad7205b

### PR DESCRIPTION
**Pull request by alfopisano**
Closes #1766

## Motivation
We had to implement the daily rewards UI design.

## Summary of changes
Created the new scene for this screen.

Reference: 
See Jaz's comment bellow

Result: 
Screenshot 2024-05-20 at 16 34 49
Screenshot 2024-05-20 at 16 35 19

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by BertovDev** [comment]
Visual reference

Screenshot 2024-05-20 at 11 00 37 AM

**Comment by jazimp** [comment]
Updated references: @alfopisano 

reference-01
reference-02

**Comment by jazimp** [comment]
> The normal flow of the application in play mode doesn't allow the player to access the daily rewards screen yet, right?
> 
> Also, did the carbonoid image get removed from the design? I see it in [the issue page] but not in the reference picture in this PR, if so, what do you think of removing the asset altogether?

@tkz00 Here's the updated references. We removed the carbonoid image, and I forgot to update this, sorry!

DR update-01
DR update-02

**Comment by alfopisano** [comment]
> The normal flow of the application in play mode doesn't allow the player to access the daily rewards screen yet, right?
> 
> Also, did the carbonoid image get removed from the design? I see it in [the issue page](https://github.com/lambdaclass/champions_of_mirra/issues/1766) but not in the reference picture in this PR, if so, what do you think of removing the asset altogether?

Oh yes you are right!! I forgot to delete the asset, nice catch. On it

**Review by tkz00 — COMMENTED** [review]
I feel that the dragging functionality should be applied to the whole carousel, not just to the elements inside it. Like it should be possible to scroll while starting the drag on any place inside the red container from the image below. Let me know what you think!

Screenshot 2024-05-30 at 4 49 36 PM

**Comment by alfopisano** [comment]
> I feel that the dragging functionality should be applied to the whole carousel, not just to the elements inside it. Like it should be possible to scroll while starting the drag on any place inside the red container from the image below. Let me know what you think!
> 
> Screenshot 2024-05-30 at 4 49 36 PM

I agree!! Working on it

**Review by tkz00 — APPROVED** [review]
The screen looks and feels great. It has my approve.

The only thing to note is that the back button takes you to the `MainScreen` scene but throws the below shown exceptions, this is normal since the references that fail are to objects that are created on the `TitleScreen`, and the only way to access the `DailyRewards` is to modify the normal flow of the application by setting it as the starting scene, thus bypassing `TitleScreen`, and when `DailyRewards` is enabled, it will be accessed through the normal flow of the game, eliminating these errors.

image

**Review by ncontinanza — CHANGES_REQUESTED** [review]
What do you think of renaming  `GoldContainer (1)` to `GoldContainer`?
image

**Comment by alfopisano** [comment]
> Should we consider having everything inside of the safe zone, or is it ok like this? I noticed the visual reference considered some distance to the borders of the screen.
> 
> image

I think it could be nice yes if 

> What do you think of renaming `GoldContainer (1)` to `GoldContainer`? image

Sure!! My bad that it was not renamed

**Comment by alfopisano** [comment]
> Should we consider having everything inside of the safe zone, or is it ok like this? I noticed the visual reference considered some distance to the borders of the screen.
> 
> image

I would say that as long as when you enter the screen you have this margin which is the one considered on the reference it is ok:
Screenshot 2024-06-07 at 11 03 41

**Review by ncontinanza — APPROVED** [review]

**Review by tkz00 — APPROVED** [review]

**Pull request merged**
