### PR TITLE
[GH-1915] Hide login option in title screen

### LINKED ISSUE #1915: [DESIGN] Remove login option in TitleScreen
## 🎨 Design

Our login needs some more work until it's done. Until then we are not making the option available for the players. Therefore, we should hide it

### Implementation

Hide the login button until the login is totally ready

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1915 

## Motivation

The login feature needs more work

## Summary of changes

This PR hides the login option until this feature is completely functioning

## How has this been tested?

Start running the game. the option should be hidden. 
Play a match then go back to title screen. Everything should work as expected

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — CHANGES_REQUESTED** [review]
Shouldn't we also remove the _connect with google_ option from the user section on the main screen settings? 
Screenshot 2024-07-08 at 12 47 03

**Comment by AngieDutra** [comment]
Great catch! I'll do this asap

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on my iOS device

**Review by saugon — APPROVED** [review]
Tested on iphone

**Pull request merged**
