### PR TITLE
[GH-1775] Update Uma's images

### LINKED ISSUE #1775: [DESIGN] Update of Uma's image
## 🎨 Design

We need to update the current images we have of Uma

Screens: 

1. Character Info 
2. Prepare for battle
3. Kill feed

### References
Character list
CI

Prepare for battle
PfB

Kill feed
Kill feed

### Assets
https://drive.google.com/drive/folders/1jqdiJach6DrKYSpIcOh78rG66SKAjgs9?usp=drive_link

### PR DESCRIPTION
**Pull request by tkz00**
Closes #1775 

Uma's images in game were outdated, this PR adds the new assets that the art team has been working on. To check this change works, select and go into some matches with Uma and verify the new images appear in the characters list, the lobby screen and in the prepare for battle animation and the kill feed, just like the references show.

You'll find the references in [Update of Uma's image](https://github.com/lambdaclass/champions_of_mirra/issues/1775)

I've also deleted some assets that were duplicated on the project, so it's necessary to test the whole game, not just the affected areas.

How it looks in game:

Screenshot_20240716_152354_client
Screenshot_20240716_152401_client
sc
Screenshot_20240716_152656_Video Player

## Checklist
- [X] I have tested the changes locally.
- [X] I have tested the whole game after applying the changes, not only the affected areas.
- [X] I self-reviewed the changes on GitHub, line by line.
- [X] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [X] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Review by AngieDutra — COMMENTED** [review]
Does this happen to you?
Screenshot 2024-07-22 at 19 14 33

**Comment by tkz00** [comment]
> Does this happen to you? Screenshot 2024-07-22 at 19 14 33

You're right, I forgot to commit the changes to the sprite atlases.

**Review by AngieDutra — APPROVED** [review]
Nice! Tested on unity desktop and Android

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Pull request merged**
