### PR TITLE
Add level up sound

### PR DESCRIPTION
**Pull request by tkz00**
Add a sound for unit level up. On the unit detail screen, when a unit is successfully leveled up (the big blue button in the bottom) a sound should play, if the user doesn't have enough resources to make that upgrade, the sound should not play and a popup informing the user of this should appear instead.

### CODE REVIEW

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Review by ncontinanza — APPROVED** [review]

**Review by AngieDutra — CHANGES_REQUESTED** [review]
The way this sound is being used is as a click sfx and not a completed action sfx. However, it sounds as if the level up was successful even tho I have no money for that. This sound should be used as a successful action feedback. I would also add a sound to represent not successful actions but if you can't manage the time for that with just the first addition it would feel awesome

**Comment by tkz00** [comment]
> The way this sound is being used is as a click sfx and not a completed action sfx. However, it sounds as if the level up was successful even tho I have no money for that. This sound should be used as a successful action feedback. I would also add a sound to represent not successful actions but if you can't manage the time for that with just the first addition it would feel awesome

The sound now only plays on successful level ups, so that is solved. I've been trying to add another sound when the button is clicked, a more "discrete" one, that plays indifferently of the result of the request, but when the level up is successful the two sounds together don't feel right, maybe it's a matter of finding the correct sounds.

**Review by AngieDutra — APPROVED** [review]
Tested in Unity desktop and everything is working as expected ✨

**Review by ncontinanza — APPROVED** [review]

**Pull request merged**
