### PR TITLE
Update Skill Indicators

### PR DESCRIPTION
**Pull request by AngieDutra**
> [!WARNING]
> This PR should be merged alongside backend PR [Send offset from skills #762](https://github.com/lambdaclass/mirra_backend/pull/762)

## Motivation

The skill indicators were outdated

## Summary of changes

This PR updated our skill indicators in AimDirection. This implementation isn't the optimal nor the final one but it's a quick iteration to have this in game and the develop a better way to handle this assets

## How has this been tested?

Start a game and use all character's skills

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by AngieDutra** [comment]
I need to adjust sizes for valtimer skills

**Comment by AngieDutra** [comment]
I'll fix some conflicts and fix the rangeArea asset

**Comment by AngieDutra** [comment]
To take into account:
- I need some values from backend to improve uma's and muflus's indicator sizes accuratly. 
- I would also want to review hack's basic and it's projectile logic to have the indicators match better. 
- The entire code should be refactor in the near future.

**Comment by AngieDutra** [comment]
I'll ask for the backend PR and update the colors based on what the art team submits today

**Comment by AngieDutra** [comment]
I created an issue for the missing things:
- a future refactor
- have all indicators use backend values

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on my iOS device and I really like this new designs

**Review by tkz00 — APPROVED** [review]
Great! Tested on android. I've left some comments/corrections for future iterations here: https://github.com/lambdaclass/champions_of_mirra/issues/1928#issuecomment-2225901495

**Pull request merged**
