### PR TITLE
UI fix popups

### LINKED ISSUE #267: [DESIGN] Pop-ups fix guide
## 🎨 Design

To begin organizing the usage of pop-ups, we could establish two types:

**Pop-up 1:**

It can be the most common pop-up, it should be used in cases where a lot of information is displayed.

- It should cover 90% approximately, of the screen (in height and width).
- It should have a header, as clear and concise as possible.
- It can have a close button (make sure there is no other button that performs the same action).
- Behind the pop-up, there should be a black layer with 80% opacity, to aid in reading it and help the user understand that they are viewing a pop-up.
- There should be padding between borders and content.

**Pop-up 2:**

Its use should be for more specific actions, where the user has 2 similar options like "accept" and "cancel".

- It should be 50% smaller than the main one (approximately).
- It should have a header, as clear and concise as possible.
- Behind the pop-up, there should be a black layer with 80% opacity, to aid in reading it and help the user understand that they are viewing a new pop-up.
- There should be padding between borders and content.

### PR DESCRIPTION
**Pull request by tkz00**
Closes #267 

The popups had to be unified into prefabs so they would be easier to modify, and also they needed visual improvements, both these things are done in this PR.

Screenshot 2024-03-25 at 15 16 21
Screenshot 2024-03-25 at 15 16 31
Screenshot 2024-03-25 at 15 16 36
Screenshot 2024-03-25 at 15 16 44
Screenshot 2024-03-25 at 15 16 53
Screenshot 2024-03-25 at 15 16 58
Screenshot 2024-03-25 at 15 17 10
Screenshot 2024-03-25 at 15 17 20
Screenshot 2024-03-25 at 15 17 26
Screenshot 2024-03-25 at 15 17 32
Screenshot 2024-03-25 at 15 17 42

### CODE REVIEW

**Review by AngieDutra — CHANGES_REQUESTED** [review]
This sections requiere a black overlay with a certain transparency. The rest is looking good ✨

**Review by AngieDutra — DISMISSED** [review]
Awesome! ✨ I love this

**Comment by jazimp** [comment]
They look very good, great job!

**Comment by martinacantaro** [comment]
Leaving some notes that might turn into tickets:
- For the "Can't rank up unit" popup, it would be nice for the user to receive more information about why it's not possible. I think we don't have this info yet because the backend only returns `cant_rank_up`

Screenshot 2024-04-03 at 12 52 31

- In the Item Detail popup, the "+50 hp" text should be aligned with the rest of the item information.

Screenshot 2024-04-03 at 16 39 25

**Comment by martinacantaro** [comment]
In the Campaign screen, the Battle button is off center
Screenshot 2024-04-03 at 18 31 34

**Comment by tkz00** [comment]
> In the Campaign screen, the Battle button is off center Screenshot 2024-04-03 at 18 31 34

Don't know what caused it, but now it's fixed!

**Review by martinacantaro — APPROVED** [review]
All done! LGTM

**Pull request merged**
