### PR TITLE
Add Otix to the game

### PR DESCRIPTION
**Pull request by BertovDev**
This PR adds Otix mode, prefab, materials, textures and animations.

Since this only adds the asset's for Otix, there should be no change in the game itself, check the game flow continues as normal and matches can be played without issues.

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — APPROVED** [review]
Nice!! Could play on an iOS build without any issues

**Review by AngieDutra — COMMENTED** [review]
Questions:
- What is the difference between the fbx? Are we using both or any?
Screenshot 2024-06-24 at 17 33 00

- The following fbx don't have materials. Are they being used?
Screenshot 2024-06-24 at 17 33 23

I ask to avoid merging unused assets

**Comment by tkz00** [comment]
> Questions:
> 
>     * What is the difference between the fbx? Are we using both or any?
> 
> 
> Screenshot 2024-06-24 at 17 33 00
> 
>     * The following fbx don't have materials. Are they being used?
> 
> 
> Screenshot 2024-06-24 at 17 33 23
> 
> I ask to avoid merging unused assets

"Minion A" and "Minion B" have been removed. In respect to the first comment, there are two versions of Otix's minions, one for the in game model, and one for the UI one (CenterofWorld), they have different anchors which is necessary to more easily position them during animations.

**Comment by AngieDutra** [comment]
Oh I see. Awesome! I'll review again asap

**Review by alfopisano — APPROVED** [review]

**Comment by alfopisano** [comment]
Tested on iOS build

**Pull request merged**
