### PR TITLE
[VFX] Unified character shader to avoid conflicts v2

### PR DESCRIPTION
**Pull request by saugon**
Based on: https://github.com/lambdaclass/champions_of_mirra/pull/1955

## Motivation

There were many versions of the character shader, so I combined them all together and merged them back into all branches. Now, all branches contain the same version of the shader and almost the same versions of materials to avoid conflicts when merging all these branches into the main branch. The character shader is now cleaner due to using subgraphs for each feature. This helps keep the shader unchanged when you need to modify a feature. The pull request also contains set up character materials, some textures for it, and a new Otix material. This pull request should be merged first.

## Summary of changes

- unified version of characters shader
- set up characters materials
- added new material fot Otix

## How has this been tested?

This request doesn't contain visual changes.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by AngieDutra — COMMENTED** [review]
I have some questions:
Why does Uma's shader not have the following section? The rest of the characters do
Screenshot 2024-07-23 at 10 50 50

Why does h4ck have the death toggle in that section on? is the only character who does

**Comment by saugon** [comment]
> Why does Uma's shader not have the following section? The rest of the characters do

1. It's not the same shader.
2. This is probably addressed in the PR that’s applying the vfx. This PR is just for unifying the shaders.

**Review by tkz00 — CHANGES_REQUESTED** [review]
- H4ck's brighter that the current version.
(Current)
Screenshot_20240723_102931_Champions of Mirra

(This branch)
Screenshot_20240723_110419_client

- Muflus's weapon is also brighter than the current version.

(Original)
Screenshot_20240723_111057_Champions of Mirra

(This branch)
Screenshot_20240723_111108_client

Beyond this everything works and looks great, all characters and items have been testes on my android, just the above issues were noted.

**Comment by tkz00** [comment]
> * H4ck's brighter that the current version.
>       (Current)
>       Screenshot_20240723_102931_Champions of Mirra
> 
> 
> (This branch) Screenshot_20240723_110419_client
> 
>     * Muflus's weapon is also brighter than the current version.
> 
> 
> (Original) Screenshot_20240723_111057_Champions of Mirra
> 
> (This branch) Screenshot_20240723_111108_client
> 
> Beyond this everything works and looks great, all characters and items have been testes on my android, just the above issues were noted.

We'll revisit these differences in the future to not block other changes that require this one.

**Review by tkz00 — APPROVED** [review]

**Pull request merged**
