### PR TITLE
Fix unwanted file changes

### PR DESCRIPTION
**Pull request by BertovDev**
## Motivation

- Text mesh pro problems.

TextMeshPro dynamic font assets have a very annoying habit of saving their dynamically generated binary data in the same text file as their configuration data. This causes massive headaches for version control.

- Danger zone problem

Renderer.sharedMaterial returns the actual instance(s) of the Material at renderer.sharedMaterials[0] that is on the object.
This can be modified, and it will affect every use of this Material in the Scene.

renderer.material, on the other hand, creates a copy of renderer.sharedMaterials[0]

So with this we are not overriding the material saved in the scene.

## Summary of changes

- Prevent dynamics fonts changes to be saved
- Use material instead of shaderMaterial to do changes.
- Set rotation after instantiating the model Denial_AOE.
- Regenerate each font again as Static.

## How has this been tested?

Normal play the game, no changes of fonts and the danger zone should appear in the source control.

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — CHANGES_REQUESTED** [review]
Restores any changes from the terminal. Played on unity desktop, after the battle ended I stopped the game and saved any possible changes. When heading back to the terminal this files were modified: 
Screenshot 2024-05-15 at 16 27 09

**Review by alfopisano — CHANGES_REQUESTED** [review]
Tested as described previously and encountered the following problems: 
- This file was modified:
Screenshot 2024-05-15 at 18 23 38

- I asume it has to do with the change above but some font were looking weird:
Screenshot 2024-05-15 at 18 22 00
Screenshot 2024-05-15 at 18 21 34

**Comment by BertovDev** [comment]
> This file was modified:

Did you restart unity?

**Comment by alfopisano** [comment]
Tried restarting unity and the problem persisted.

**Review by AngieDutra — CHANGES_REQUESTED** [review]
In addition, I'm having the same issue. Pink means missing material, maybe you forgot to save something in the fix process?
Screenshot 2024-05-20 at 11 48 44

**Comment by AngieDutra** [comment]
Or maybe you need to replace the fonts one by one through the game?

**Comment by tkz00** [comment]
This PR is trying to solve two different issues, the fonts one is being handled here: [Fix dynamic font assets changing version control](https://github.com/lambdaclass/champions_of_mirra/pull/1814), the materials/textures one will be investigated and tackled later on.

**Pull request closed without merging**
