### PR TITLE
[GH-1831] Add toggle bots button

### LINKED ISSUE #1831: [FEATURE] Add button to enable/disable the BOTS
# 🚀 Feature

Add a button to enable/disable the BOTS. It will be under "dev" tab.

### PR DESCRIPTION
**Pull request by Nico-Sanchez**
> [!IMPORTANT]  
> This PR must be merged along with https://github.com/lambdaclass/mirra_backend/pull/693

Closes #1831 

## Motivation

We need a way to disable/enable the bots as pleased, for testing purposes.

## Summary of changes

- [Add new ToggleBots protobuf message](https://github.com/lambdaclass/champions_of_mirra/pull/1840/commits/86be3870a52de103eb80b086e4b7e015db0e92a3)
- [Add new ToggleBots button in battle settings controller](https://github.com/lambdaclass/champions_of_mirra/pull/1840/commits/c71e31b241589507d4417898fbf2e1240cf884df)
- [Add new ToggleBots button action in battle script and its websocket message](https://github.com/lambdaclass/champions_of_mirra/pull/1840/commits/68a38c3a15ae5a77415993dcf07faccc85fc7d52)
- [Add ToggleBots button to BattleSettingsSplash prefab](https://github.com/lambdaclass/champions_of_mirra/pull/1840/commits/e0af14d45a59e0d3004c468320b01fca82c20071)

## How has this been tested?

Just play a game and toggle BOTS in settings > dev tab.
Make sure you use the following backend branch -> https://github.com/lambdaclass/mirra_backend/pull/693

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by tkz00 — APPROVED** [review]
Great! This feature will make testing incredibly easier!

**Review by tkz00 — COMMENTED** [review]
image
Do you think something could be made to avoid this message? Or is it printed for a reason?

This happens when bots are turned on or off, since the toggle bots message that the backend broadcasts isn't handled in `GameServerConnectionManager.cs`

**Comment by Nico-Sanchez** [comment]
> image Do you think something could be made to avoid this message? Or is it printed for a reason?
> 
> This happens when bots are turned on or off, since the toggle bots message that the backend broadcasts isn't handled in `GameServerConnectionManager.cs`

I didn't add this print and I find it useful. You can see in your console any unhandled message you receive.

**Comment by tkz00** [comment]
> > image Do you think something could be made to avoid this message? Or is it printed for a reason?
> > This happens when bots are turned on or off, since the toggle bots message that the backend broadcasts isn't handled in `GameServerConnectionManager.cs`
> 
> I didn't add this print and I find it useful. You can see in your console any unhandled message you receive.

Yeah, I meant to disable the print specifically for the message `ToggleBots` to not clog the console, since it's normal the client doesn't handle it, I believe the correct way of "handling" that message is doing nothing, and leaving the log for any other unexpected messages, but if you feel it's better to leave it for visibility it's ok too.

**Comment by Nico-Sanchez** [comment]
> > > image Do you think something could be made to avoid this message? Or is it printed for a reason?
> > > This happens when bots are turned on or off, since the toggle bots message that the backend broadcasts isn't handled in `GameServerConnectionManager.cs`
> > 
> > I didn't add this print and I find it useful. You can see in your console any unhandled message you receive.
> 
> Yeah, I meant to disable the print specifically for the message `ToggleBots` to not clog the console, since it's normal the client doesn't handle it, I believe the correct way of "handling" that message is doing nothing, and leaving the log for any other unexpected messages, but if you feel it's better to leave it for visibility it's ok too.

Oh I get what you mean, you're totally right. I'll fix it.

**Review by tkz00 — COMMENTED** [review]
Since I'm having problems with my testing environment, I haven't been able to test this, I'll come back when that issue is solved.

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on an iOS build and worked great!!

**Review by manucamejo — APPROVED** [review]

**Pull request merged**
