### PR TITLE
Websocket backend connection & communication

### LINKED ISSUE #135: Integrate front and back
Based on our new PR to the game_backend repo, integrate with what we have in Unity

### PR DESCRIPTION
**Pull request by tkz00**
Closes #135 

## Motivation

We moved from communicating between the backend and client with http requests to a websocket based approach, this saves us the overhead that http requests have, it's faster.

## Summary of changes

Moved a lot of logic around, User, Item, Lineup and Battle functionalities now go through the SocketConnection.cs script.

## How has this been tested?

Battle in the campaign, selecting and unselecting units, leveling up, equiping and unequiping items to units.

## Checklist
- [X] I have tested the changes locally.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by martinacantaro — CHANGES_REQUESTED** [review]
### Bug: trying to level up item when you can't afford it breaks the currency counter in the frontend
To reproduce:
- Go to Barracks, select a unit to go into the Unit Detail scene.
- Equip an item, level it up and _continue_ clicking on the level up after the "cant_afford" console message.
- Then unequip the item. Look at the currency counter in the header, it's now negative.

**Review by martinacantaro — CHANGES_REQUESTED** [review]
### Bug: in the Battle scene, all units appear locked if you emptied your formation before

To reproduce:
- Go into Campaigns > Battle
- Unselect all the units (take them all out of the battlefield)
- Go back to the Campaign scene
- Go into Battle again. Now the unit icons are all locked.

**Review by martinacantaro — DISMISSED** [review]
pls replace the glove asset

**Comment by tkz00** [comment]
> pls replace the glove asset

I've removed the glove asset from the Resources folder, now it's referenced from the ThirdParty folder where it won't be pushed to the repo.

**Review by martinacantaro — APPROVED** [review]
lgtm!

**Pull request merged**
