### PR TITLE
Fix level rewards

### PR DESCRIPTION
**Pull request by tkz00**
Show's rewards after beating a level.

### CODE REVIEW

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Tried this PR and just by the description worked fine. However, I believe while fixing conflicts the references got lost
Captura de pantalla 2024-03-15 a la(s) 6 56 51 p  m
Captura de pantalla 2024-03-15 a la(s) 7 01 43 p  m

It doesn't matter the PR tackles just a small feature. In each PR all features and functionalities should be tested just in case something like this happens it doesn't end up in main branch

**Comment by tkz00** [comment]
> Tried this PR and just by the description worked fine. However, I believe while fixing conflicts the references got lost Captura de pantalla 2024-03-15 a la(s) 6 56 51 p  m Captura de pantalla 2024-03-15 a la(s) 7 01 43 p  m
> 
> It doesn't matter the PR tackles just a small feature. In each PR all features and functionalities should be tested just in case something like this happens it doesn't end up in main branch

Solved, the afk reward's popup doesn't have any functionality, but now it doesn't throw exceptions.

**Review by AngieDutra — APPROVED** [review]
Tested in Unity desktop and it works fine! ✨

**Review by ncontinanza — APPROVED** [review]

**Pull request merged**
