### PR TITLE
Remove old name from popup name prefab

### PR DESCRIPTION
**Pull request by tkz00**
Changes the old name to the new one in the popup to enter your name.

## Checklist
- [X] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on iOS device

**Review by AngieDutra — COMMENTED** [review]
You have overrides in Player Name Input (changed in this PR)
Screenshot 2024-08-05 at 18 21 46

While at it you could solve the rest of the overrides but let me know what you think
Screenshot 2024-08-05 at 18 22 09

**Review by AngieDutra — APPROVED** [review]
LGTM Tested in Android

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on my iOS device

**Pull request merged**
