### PR TITLE
Fix JWT issues when changing servers

### PR DESCRIPTION
**Pull request by AminArria**
## Motivation

Currently in a client if you get a JWT for one server and then change servers the client will try to re-use that same JWT. In the case of Brazil and Europe it would work cause currently they share gateway server, but if you go from localhost to Europe then you face problems. Essentially when you try to go across gateway servers and have a JWT in your client 

## Summary of changes

- Extend `SelectServerIP` to change the gateway server to use and the PlayerPrefs key where the JWT for that server is stored
  - Now `CUSTOM` expects 2 IPs, arena and server in a format `arena_ip gateway_ip` (notice the space, also gateway needs the http/https part)
- Extend `ServerUtils` to use the new information in `SelectServerIP`
- Small cleanup of unneeded `IP` prefabs

## How has this been tested?

To test this play across servers without clearing PlayerPrefs or app data

To test with Ngrok you will need to extend your configuration to be able to handle both tunnels. You can modify you ngrok config with `ngrok config edit` and putting
```yaml
tunnels:
  arena:
    proto: http
    addr: 4000
  gateway:
    proto: http
    addr: 4001
```

And then you can do `ngrok start --all`

## Checklist
- [x] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by tkz00 — CHANGES_REQUESTED** [review]
https://github.com/lambdaclass/champions_of_mirra/assets/67983386/aa477ad4-7e63-4a94-a0fe-cbe4cd7f15b8

I can't go through the title screen when setting the custom server, but when using the Brazil one it works fine.

**Comment by ncontinanza** [comment]
> muted.mp4 
> I can't go through the title screen when setting the custom server, but when using the Brazil one it works fine.

@AminArria please explain in the log that the input should be `ARENA_IP https://GATEWAY_IP`

**Review by ncontinanza — APPROVED** [review]

**Comment by tkz00** [comment]
> muted.mp4
> 
> I can't go through the title screen when setting the custom server, but when using the Brazil one it works fine.

This was because `https://` was missing from the second URL

**Review by tkz00 — CHANGES_REQUESTED** [review]
https://github.com/lambdaclass/champions_of_mirra/assets/67983386/c3982a96-6876-498f-a1e8-cbcd2e4e47b8

Screenshot 2024-06-14 at 5 47 27 PM


I can't go past the title screen now, sometimes I go through to the mainscreen but can't enter a match, and sometimes I can play matches, but generally it doesn't work.

**Review by tkz00 — APPROVED** [review]
Great, works good on my android device. For anyone reading this, I don't know if it has something to do with having multiple ngrok tunnels, or something related to my phone, but it takes me several minutes to login from the title screen, after that you can play normally, but just a disclaimer, since I believed this PR didn't work because of this.

**Pull request merged**
