### PR TITLE
[GH-1742] Muflus fire in UI

### LINKED ISSUE #1742: [REFACTOR] Muflus should have fire in UI
## 🚧 Refactor

The Muflus in UI should have the same fire vfx as the one in game.

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1742 

## Motivation

Muflus's fire was missing in the UI

## Summary of changes

https://github.com/lambdaclass/champions_of_mirra/assets/82987608/9b435dc4-46d7-494e-82f6-dd54f32e0bf4

## How has this been tested?

This fire in the UI should show in:
- main screen
- character info screen
- death splash 

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by AngieDutra** [comment]
I have one comment up for debate:
We have images smaller that the max size. I think the muflus's fire assets could be smaller without loosing quality in the mobile game but they don't present a huge difference and work well as they are now too
Screenshot 2024-06-14 at 15 17 55

**Review by alfopisano — DISMISSED** [review]
Nice!! Played on my iPhone and worked great

**Comment by tkz00** [comment]
I feel the fire in the head seems kind of weird, like it's another art style than the 3D model, also it seems to grow to the inside, like a cone with it's pointy end to the top. I've raise these concerns to the art team and will wait on their response to continue with the review.

**Comment by AngieDutra** [comment]
I talked with the art team and they decided to move forward with this PR as it is and later on try to improve it since the vfx team has other priorities at the moment

**Review by tkz00 — COMMENTED** [review]
Everything works and looks great, I've set the head fire textures max size parameter to 64 and I see no difference, is this normal? Should this value be set lower?

**Comment by AngieDutra** [comment]
I believe it could afford to be lower. The accurate way to test this would be in a mobile build. Do you have screens for both cases? So I can check if there is really no difference?

**Comment by AngieDutra** [comment]
Here are my tests. IMO there is a noticeable difference
High quality:
Screenshot_20240624_151316_client
Low quality:
Screenshot_20240624_151849_client
I'll try out a middle quality just to find a happy middle ground

**Comment by AngieDutra** [comment]
Tested 64 and it looks good. Let me know what you guys think

**Review by tkz00 — APPROVED** [review]
Screenshot_20240624_163008_client
Looks good on my android device.

**Review by alfopisano — APPROVED** [review]
Nice!! Also looks good on my iPhone

**Pull request merged**
