### PR TITLE
[GH-1831] Add button to toggle bots

### LINKED ISSUE #1831: [FEATURE] Add button to enable/disable the BOTS
# 🚀 Feature

Add a button to enable/disable the BOTS. It will be under "dev" tab.

### PR DESCRIPTION
**Pull request by Nico-Sanchez**
> [!IMPORTANT]  
> This PR must be merged along with https://github.com/lambdaclass/mirra_backend/pull/693

Closes #1831 

## Motivation

We need a way to disable/enable the bots as pleased, for testing purposes.

## Summary of changes

- [Add ToggleBots to messages.proto](https://github.com/lambdaclass/champions_of_mirra/pull/1833/commits/e3411e99ee8254dee0d743d2da6395d5786b9422)
- [Add new button and message to make server toggle bots](https://github.com/lambdaclass/champions_of_mirra/pull/1833/commits/e87acd4eb1a59030708ab4eccf73480c184d8159)
- [Group server and client toggle bots to single message ToggleBots](https://github.com/lambdaclass/champions_of_mirra/pull/1833/commits/01172cfe2f6cc3e5d070919672ce85204d94102e)

## How has this been tested?

Just play a game and toggle BOTS in settings > dev tab.
Make sure you use the following backend branch -> https://github.com/lambdaclass/mirra_backend/pull/693

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — CHANGES_REQUESTED** [review]
When I moved to the branch I ton of errors appeared on my console:
Screenshot 2024-06-12 at 13 47 06
Was able to fix this by running make generate-protos to re-generate them.

After that I could start a battle but when trying to access the settings I was not able to do so:
https://github.com/lambdaclass/mirra_backend/assets/116388676/9c148a04-9478-4635-888e-7289cb0e5dfb
I think you deleted the battle setting splash

**Comment by Nico-Sanchez** [comment]
> Nice!! Was able to use the button correctly but I think we have a small issue at the beginning of the battle. When starting the bots are active, but when looking at the setting the toggle looks as if they were off. After pressing the button the bots keep active and if after that we press the toggle again then the bots stop attacking.
> 
> I think we should either start with the toggle on and the bots active or all the opposite way, what do you think?
> 
>  Screen.Recording.2024-06-12.at.17.07.49.mov

This is a known issue and will be fixed in other PR -> https://github.com/lambdaclass/champions_of_mirra/pull/1834
We can merge it as it is for now

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on unity editor and iOS build

**Comment by Nico-Sanchez** [comment]
Due to a buttons refactor in main, I'm closing this and rewrite the code in https://github.com/lambdaclass/champions_of_mirra/pull/1840

**Pull request closed without merging**
