### PR TITLE
[Gh-1922] Update item icons

### LINKED ISSUE #1922: [FEATURE] Implement new items icons and update items vfx colors
### Motivation

The icons are not representative of our items

### Implementation

Implement the new icons sumbitted by the art team:
https://drive.google.com/drive/folders/1TAjZNMpuActYFvkIh1FC2zlGKpl0XWv1

Adjust the items vfx colors based on the new item icons

### Additional context
Check this with art team before setting the PR as ready to review

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1922

## Motivation

The item icons are outdated and do not represent the items functionality

## Summary of changes

This PR changes:
- item icons
- clock vfx colors
- boots vfx colors

https://github.com/user-attachments/assets/1ff430df-0a16-4489-84f0-8700c20fefda

## How has this been tested?

Try using all items. To test this quicker change in backend the `item_spawn_interval_ms` value to 1000

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on my iOS device and all items look amazing

**Review by tkz00 — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/896c0d12-aab0-42f4-93fc-d1abf12902c0

I felt the pick up/use item animations are weird, I've consulted with the art team and it was decided that a better animation should be implemented before merging this.

**Comment by jazimp** [comment]
Visual approval ✅

**Review by ncontinanza — APPROVED** [review]
LGTM! Tested locally and in Android, everything worked great and looked like in the reference.

**Review by tkz00 — APPROVED** [review]
Looks great! Tested on my android.

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Pull request merged**
