### PR TITLE
Battle with Dynamic Number of Units

### LINKED ISSUE #368: Battles with dynamic number of units
Currently, if a battle with less than 6 units in any of the teams (the maximum number of units per team), the client breaks, the battle screen scripts should be modified to allow for this behavior.

### PR DESCRIPTION
**Pull request by tkz00**
Closes #368 

## Motivation

If a battle was played fought with less than six units on either team, the client would break, this had to be fixed since the player could choose to fight with less than the max number of units, or maybe a level could have less than six, even if these weren't the cases, is allows for better manual testing of the application.

## Summary of changes

The problem lied on the `BattleManager.cs` script breaking since in certain points it searches through the collection of `BattleUnits` searching for one with certain unit `id`, this caused a Null Reference Exception since when less than twelve units in total started the battle some `BattleUnit` will have a null `selectedUnit` reference thus causing the exception when trying to access the `id` field of the unit.

To fix this, whenever a specific `BattleUnit` is searched by its unit's `id` an additional filtering is applied to look for the ones that have a `selectedUnit` assigned.

## How has this been tested?

Go to the lineup screen of a level and remove some of the units on your team, then let the fight the battle, it should play out as normal and don't break. The same should be done by removing some of the units of a level in the local backend, then fighting that level and checking nothing breaks, this could be done by getting the `level_id` of the level where you are going to test this, go to the unit's table and search for the ones with that `level_id` and delete one or more, then try to fight that level on the client, checking everything works as normal.

### CODE REVIEW

**Review by ncontinanza — CHANGES_REQUESTED** [review]
Watch out that now you can start a battle with 0 units. This should be also checked in the backend, I opened this issue: https://github.com/lambdaclass/champions_of_mirra/issues/417

**Comment by tkz00** [comment]
> Watch out that now you can start a battle with 0 units. This should be also checked in the backend, I opened this issue: #417

You are right! Already fixed from the client's side, the button becomes non-interactable when 0 units are selected for the player.

**Review by ncontinanza — APPROVED** [review]
Excellent!

**Review by martinacantaro — APPROVED** [review]
approved!
I reviewed it with 
5 v 6
6 v 5
1 v 1

**Pull request merged**
