### PR TITLE
[GH-1867] Fix unwanted modified materials

### LINKED ISSUE #1867: [BUG] Unwanted modified files
## 🐛 Bug Report

Some files are being modified without the intention of it such as:

- sand material
- aoe hack effect 

### Steps to Reproduce

run the game and play till the end

It could be the changing of materials in runtime

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1867 

## Motivation

There are some files changing in runtime due to shared material modifications

## Summary of changes

This PR changes every sharedMaterial modification to material

## How has this been tested?

Try triggering h4ck's or valtimer's aoe skills and the zone. There should not be modified files

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by alfopisano — CHANGES_REQUESTED** [review]
When playing as Valtimer the following file was modified:
Screenshot 2024-07-12 at 13 56 47

This was playing locally in Brazil

**Comment by AngieDutra** [comment]
I could reproduce this. Does this happen if you restart Unity too?

**Comment by tkz00** [comment]
> When playing as Valtimer the following file was modified: Screenshot 2024-07-12 at 13 56 47
> 
> This was playing locally in Brazil

This, I'm pretty sure, is an unrelated problem, the file changed in this picture is a prefab, probably is being modified programmatically but in other part of the code, since from my understanding this PR scope is only to avoid materials being modified inadvertently, I would suggest the issue raised here should be handled on other PR, the scope should be changed to "Fixing unwanted asset modifications".

**Review by tkz00 — COMMENTED** [review]
Should the `sharedMaterial` modifications in the `DamageZoneManager.cs` script also be changed to `material`? Or where they left like that because of something?

**Review by ncontinanza — APPROVED** [review]
LGTM! I tested locally and didn't see any changes. I also tested in iOS and everything was working fine.

**Pull request merged**
