### PR TITLE
[GH-1743] Create profile screen

### LINKED ISSUE #1743: [FEATURE] Profile screen
## 🚀 Feature

Implement profile screen design

### Reference

Reference

### Assets

Screen assets: https://drive.google.com/drive/folders/13Bio6chHgmhaRTCEU0L8SvGz50j4bU3E?usp=drive_link
Buttons: https://drive.google.com/drive/folders/1h93h0kjVentkQGeoLqCXmc7HB0Y7pBGr?usp=drive_link
Background: https://drive.google.com/file/d/1eFqlzO_FEwWpKGlU_ErkWmjp6KKu0YEN/view?usp=drive_link
Color guide: https://drive.google.com/file/d/1kfNP9SAHgsoHycKfF__KXcExaIXd-nFs/view?usp=drive_link

### Additional 

When using the name change pop-up, correct the typography variable for the title: "Welcome to Curse of Mirra!" / "Your name, your choice!" (typography: source sans 3 variable: bold)

### PR DESCRIPTION
**Pull request by alfopisano**
Closes #1743

## Motivation
Needed to create the profile UI.

## Summary of changes
Added the new Profile screen scene. Also added the option to edit the name of the user on the profile screen.

Reference: 
Reference

Result: 
Screenshot 2024-05-14 at 17 08 21

Name selector: 
Screenshot 2024-05-14 at 17 50 54

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by jazimp** [comment]
Visual approval ✅

**Review by BertovDev — CHANGES_REQUESTED** [review]
Nice and only some changes.

- Text reference is missing

Screenshot 2024-05-15 at 10 58 52 AM

- The minion and name container in Mainscreen should send you to this Profle scene.

Everything else seems to be working well.

**Comment by BertovDev** [comment]
Also the slider in the rank is interactable it should not.

**Review by BertovDev — CHANGES_REQUESTED** [review]
Nice and just last issues with the responsiveness of the text and the screw in the left.

Here is a pick from the my phone build:
Screenshot_20240515_135824_client

To fix this you can change the left values of the text to 0. In the Alignment set it to left and adjust the margins. I believe with that should work.

**Comment by BertovDev** [comment]
Also if you can merge main to it.

**Review by BertovDev — CHANGES_REQUESTED** [review]
Awesome last change and we ready. if you touch a little outside the container you are able to enter the changeName container.

To fix this we can change the edit container width as something like `890`

**Review by BertovDev — APPROVED** [review]

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Nice! A few suggested changes:
- Looks like you misplaced a script. It should be in `Scripts > UI` folder
Screenshot 2024-05-20 at 10 49 23

- I usually add the UI managers to the parent prefab instead of creating a gameObject just to add a script to reduce the GameObjects in the scene to just have what we really need. I don't see this as an issue because we do it in Battle.cs but I don't see it as necessary here since it's by far less complex
Screenshot 2024-05-20 at 10 50 21

- You missed a max size in profile asset
Screenshot 2024-05-20 at 10 55 08

- You have repeated assets. You could use just one and in the settings case add a canvas group and set it to 50%
Screenshot 2024-05-20 at 10 55 15
Screenshot 2024-05-20 at 10 55 23

**Comment by alfopisano** [comment]
> Nice! A few suggested changes:
> 
> * Looks like you misplaced a script. It should be in `Scripts > UI` folder
> 
> Screenshot 2024-05-20 at 10 49 23
> * I usually add the UI managers to the parent prefab instead of creating a gameObject just to add a script to reduce the GameObjects in the scene to just have what we really need. I don't see this as an issue because we do it in Battle.cs but I don't see it as necessary here since it's by far less complex
> 
> Screenshot 2024-05-20 at 10 50 21
> * You missed a max size in profile asset
> 
> Screenshot 2024-05-20 at 10 55 08
> * You have repeated assets. You could use just one and in the settings case add a canvas group and set it to 50%
> 
> Screenshot 2024-05-20 at 10 55 15 Screenshot 2024-05-20 at 10 55 23

Nice!! Did the changes but left the Max Size as 2048 for the Profile asset because it is the background of the screen. Renamed the asset to make it clearer.

**Review by tkz00 — CHANGES_REQUESTED** [review]
Found a couple issues:

1. I get this log constantly when I enter the profile screen
Screenshot 2024-05-30 at 5 24 53 PM

2. The margin between the "Highest Prestige" and "Games Won" containers and the separator on top grows smaller when changing phones/resolution. The first pic is from my Samsung Galaxy S10+ and the second is from the Unity editor with the iPhone 12 mini simulator.
sc
Screenshot 2024-05-30 at 5 36 52 PM

3. Also found that in tablets the screen doesn't look good.
Screenshot 2024-05-30 at 6 27 30 PM

**Review by tkz00 — APPROVED** [review]
Looks great!

**Review by tkz00 — CHANGES_REQUESTED** [review]
- This is the name for the title of the rename popup in the Profile screen, do you think it could be changed to "Title"? And the element below it, which is "Title" renamed to "Description" or something like that?
Pasted Graphic
- Also there is a disabled Input game object inside InputContainer, does it serve any purpose?
Pasted Graphic 4

**Comment by alfopisano** [comment]
> * Title

Done!! The disabled input game object was not serving any propose!!

**Review by tkz00 — APPROVED** [review]
Great! Looks amazing!

**Review by ncontinanza — APPROVED** [review]
LGTM! Tested both locally and in an Android build, it's looking great.

**Pull request merged**
