### PR TITLE
Kaline Tree

### LINKED ISSUE #373: [FEATURE] Kaline Tree scene
## 🚀 Feature

Implement the Kaline Tree scene, where a user will be able to see every AFK reward rate, claim AFK rewards and level up the Kaline Tree to unblock different game features.

### PR DESCRIPTION
**Pull request by ncontinanza**
Closes #373 

## Summary of changes

- Add Kaline Tree scene, where users will be able to:
   - Get their available AFK rewards and claim them (implemented in this PR)
   - See their AFK reward rates (currently a placeholder, will be implemented in a future PR)
   - Level up the tree (currently a placeholder, will be implemented in a future PR)

## How has this been tested?

Start the game with the backend in the main branch, and go to the Kaline Tree scene from the Overworld. Check that the AFK rewards functionality is still working as expected (you'll need to fight and win at least one battle for this).

## Checklist
- [X] I have tested the changes locally.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by martinacantaro — APPROVED** [review]
Functional review approved!

**Review by tkz00 — CHANGES_REQUESTED** [review]
image

Looks and works great! The only thing is that there is a broken `KalineTreeManager` game object in the overworld scene that shouldn't be there.

**Comment by ncontinanza** [comment]
> Looks and works great! The only thing is that there is a broken `KalineTreeManager` game object in the overworld scene that shouldn't be there.

Oops, should be fixed now

**Review by tkz00 — APPROVED** [review]
Great, looks amazing

**Review by martinacantaro — APPROVED** [review]
functional review approved!

**Pull request merged**
