### PR TITLE
Win and defeat screen aesthetics

### PR DESCRIPTION
**Pull request by martinacantaro**
Improve the looks of the win and defeat screens

Screenshot 2024-01-05 at 22 24 19

Screenshot 2024-01-05 at 22 23 35

### CODE REVIEW

**Review by ncontinanza — CHANGES_REQUESTED** [review]
Looking good!
Just notice that the button both from the victory and the defeat screen are not mapped to a function when they're clicked. You can only go back to the Overworld scene by clicking somewhere else on the screen.


https://github.com/lambdaclass/champions_of_mirra/assets/17294394/be82b8b8-6032-4a14-9156-271720594493

**Comment by martinacantaro** [comment]
> Just notice that the button both from the victory and the defeat screen are not mapped to a function when they're clicked. You can only go back to the Overworld scene by clicking somewhere else on the screen.

This is not in the scope of this PR because we don't yet have the campaign logic that would allow us to have different stages to progress to.  I've created a ticket for that: https://github.com/lambdaclass/champions_of_mirra/issues/69

**Comment by martinacantaro** [comment]
closes https://github.com/lambdaclass/champions_of_mirra/issues/40

**Review by ncontinanza — APPROVED** [review]
Nice!

**Review by ncontinanza — APPROVED** [review]

**Review by ncontinanza — DISMISSED** [review]

**Review by lotuuu — APPROVED** [review]
Approving since @ncontinanza's review is bugged

**Review by ncontinanza — APPROVED** [review]

**Pull request merged**
